---
on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - 'Dockerfile'
      - 'Containerfile'
  workflow_dispatch:
  schedule:
  - cron: '0 23 * * *'

jobs:
  build-container:
    runs-on: docker
    container:
      image: vel.heimsbakk.no/containers/runner-debian:latest

    env:
      STORAGE_DRIVER: vfs
      BUILDAH_FORMAT: docker
      BUILDAH_ISOLATION: chroot

    steps:
      - name: Get container registry path
        run: |
          REGISTRY_PATH=${{ env.GITHUB_SERVER_URL }}
          REGISTRY_PATH=$(echo ${REGISTRY_PATH} | sed "s#https://##g")/${{ github.repository_owner }}
          echo REGISTRY_PATH=${REGISTRY_PATH} >> $GITHUB_ENV

      - name: Get repository name
        run: |
          IMAGE_NAME=${{ github.repository }}
          REPO_OWNER=${{ github.repository_owner }}
          IMAGE_NAME=$(echo ${IMAGE_NAME} | sed "s#${REPO_OWNER}/##g")
          IMAGE_NAME=$(echo ${IMAGE_NAME} | sed "s#container-##g")
          echo IMAGE_NAME=${IMAGE_NAME} >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build container
        id: build-container
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          archs: amd64, arm64
          containerfiles: |
            ./Dockerfile

      - name: Push Container when on main branch
        id: push-container
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-container.outputs.image }}
          tags: ${{ steps.build-container.outputs.tags }}
          registry: ${{ env.REGISTRY_PATH }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Print container url when on main branch
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: echo "Image pushed to ${{ steps.push-container.outputs.registry-paths }}"
